### ISSUE TITLE
Could have included requirements.txt as i had difficulty in installing those manually🙂

### ISSUE THREAD

**Issue by taj0023** [LogicLady/SocialProfiles#1]

**Comment by taj0023** [comment]
ModuleNotFoundError: No module named 'intercom.client'

**Comment by JessiLynnCook** [comment]
@taj0023 - Oh my God, I never thought somebody would stumble across this, I apologize! I am a newbie programmer by professional standards, but when I created this app and got such great results for free, that costed money everywhere i looked, I couldn't help but post up some info. If this is something you are genuinely interested in getting up and running, let me know and I would be happy to go back through and provide thorough documentation / make sure it is still functional.

**Comment by taj0023** [comment]
Sorry for disturbing you.... I too was a newbie too back then , didn't even knew to `pip install stuff` . It was solved , and thanks for the response :)
